#cspell:ignore buildx
name: Build and Push Docker image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/emergency-contacts-print-qr:latest
          no-cache: true
          build-args: |
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            DOMAIN=${{ secrets.DOMAIN }}
            FB_PROJECT_ID=${{ secrets.FB_PROJECT_ID }}
            FB_CLIENT_EMAIL=${{ secrets.FB_CLIENT_EMAIL }}
            FB_PRIVATE_KEY=${{ secrets.FB_PRIVATE_KEY }}
